### ISSUE TITLE
New names!

### ISSUE THREAD

**Issue by eminarican** [exitflynn/distrOS#2]
cosmOS logOS thermOS
also albatross but has 2 s'

**Comment by scuderia666** [comment]
nice ideas dude!

**Comment by exitflynn** [comment]
haha love these, will be adding them in right noww

**Comment by eminarican** [comment]
ah and atmOS?

**Comment by exitflynn** [comment]
wow, that sounds REALLY rad imo. Easily in my top 10. Added!

**Comment by exitflynn** [comment]
(つ▀¯▀)つ will be closing this issue now, feel free to add on if or when you get more of these :P

**Comment by eminarican** [comment]
realized that there was a holiday named muertOS in Brasil @exitflynn

**Comment by eminarican** [comment]
maybe caicOS from "Turks and Caicos" isles?

**Comment by eminarican** [comment]
CalypsOS

**Comment by eminarican** [comment]
a bit pun but, dangeriOS

**Comment by exitflynn** [comment]
yeap added these in :)
though i went for DangerOS instead of DangeriOS if you don't mind, _HEY IT STILL SOUNDS LIKE DANGEROUS!!_
